// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvQ0ujmgYcZc9h3RsLHpLhql4Pbpq_hBc',
    appId: '1:683558866018:android:71c602731733b9cb16153b',
    messagingSenderId: '683558866018',
    projectId: 'chat-app-a3205',
    databaseURL: 'https://chat-app-a3205-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-a3205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhyFmQ9p_GqTX-QgCVaLhQVAcXXqi6FFQ',
    appId: '1:683558866018:ios:2b1cb4fcbb82ab1716153b',
    messagingSenderId: '683558866018',
    projectId: 'chat-app-a3205',
    databaseURL: 'https://chat-app-a3205-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-a3205.appspot.com',
    iosClientId: '683558866018-1l1bv5lin1hjvb0j5vrku3l78piga5ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
